modLoader = "javafml" #mandatory
loaderVersion = "${version_range_loader}"
license = "MIT"
issueTrackerURL = "https://github.com/Yamahari/ILikeWood-BiomesOPlenty-Plugin/issues" #optional

[[mods]] #mandatory
modId = "ilikewoodxbyg" #mandatory
version = "${version}" #mandatory
displayName = "I Like Wood - Oh The Biomes You'll Go Plugin" #mandatory
displayURL = "https://www.curseforge.com/minecraft/mc-mods/i-like-wood-biomes-o-plenty-plugin" #optional
logoFile = "logo.png" #optional
credits = "Yamahari and the people of Forge" #optional
authors = "Yamahari" #optional
description = '''
Adds Oh The Biomes You'll Go support for I Like Wood.
'''

[[dependencies.ilikewoodxbyg]]
modId = "forge"
mandatory = true
versionRange = "${version_range_forge}"
ordering = "NONE"
side = "BOTH"

[[dependencies.ilikewoodxbyg]]
modId = "minecraft"
mandatory = true
versionRange = "${version_range_mc}"
ordering = "NONE"
side = "BOTH"

[[dependencies.ilikewoodxbyg]]
modId = "ilikewood"
mandatory = true
versionRange = "${version_range_ilw}"
ordering = "NONE"
side = "BOTH"

[[dependencies.ilikewoodxbyg]]
modId = "byg"
mandatory = true
versionRange = "${version_range_byg}"
ordering = "NONE"
side = "BOTH"